<template>
  <v-container>
    <v-btn color="primary" @click="showDialog">Add Volunteer</v-btn>
    <v-data-table :headers="headers" :items="tableData" class="elevation-1"></v-data-table>

    <!-- Dialog for Adding a Volunteer -->
    <v-dialog v-model="dialog" persistent max-width="600px">
      <v-card>
        <v-card-title>
          <span class="headline">Add New Volunteer</span>
        </v-card-title>
        <v-card-text>
        <!-- You typically wouldn't include VolunteerID if it's auto-generated -->
        <v-col cols="12" sm="6">
          <v-text-field v-model="newVolunteer.FirstName" label="First Name"></v-text-field>
        </v-col>
        <v-col cols="12" sm="6">
          <v-text-field v-model="newVolunteer.LastName" label="Last Name"></v-text-field>
        </v-col>
        <v-col cols="12" sm="6">
          <v-text-field v-model="newVolunteer.Password" label="Password" type="password"></v-text-field>
        </v-col>
        <v-col cols="12" sm="6">
          <v-text-field v-model="newVolunteer.Email" label="Email"></v-text-field>
        </v-col>
        <v-col cols="12" sm="6">
          <v-text-field v-model="newVolunteer.Phone" label="Phone"></v-text-field>
        </v-col>
          <v-checkbox v-model="newVolunteer.HasRecordAccess" label="Has Record Access"></v-checkbox>
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="blue darken-1" text @click="closeDialog">Cancel</v-btn>
          <v-btn color="blue darken-1" text @click="saveVolunteer">Save</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      dialog: false,
      headers: [
      { text: 'Volunteer ID', value: 'VolunteerID' },
      { text: 'First Name', value: 'FirstName' },
      { text: 'Last Name', value: 'LastName' },
      { text: 'Password', value: 'Password', sortable: false }, // Typically not displayed or editable directly for security
      { text: 'Email', value: 'Email' },
      { text: 'Phone', value: 'Phone' },
      { text: 'Has Record Access', value: 'HasRecordAccess' }
    ],
    tableData: [],
    newVolunteer: {
      VolunteerID: null, // Assuming ID is auto-generated by the backend and not needed on creation
      FirstName: '',
      LastName: '',
      Password: '', // Consider security implications and proper handling
      Email: '',
      Phone: '',
      HasRecordAccess: false
    }
    };
  },
  methods: {
    showDialog() {
      this.dialog = true;
    },
    closeDialog() {
      this.dialog = false;
    },
    saveVolunteer() {
  console.log("Data being sent:", this.newVolunteer);
  axios.post('http://127.0.0.1:5000/api/volunteers', this.newVolunteer)
    .then(response => {
      this.tableData.push(response.data);
      this.newVolunteer = { FirstName: '', LastName: '', Email: '', Phone: '', HasRecordAccess: false };
      this.dialog = false;
    })
    .catch(error => {
      console.error('Error saving volunteer:', error);
      alert('Failed to save the volunteer. Please check the console for more details.');
    });
},
    fetchData() {
      axios.get('http://127.0.0.1:5000/api/volunteers')
        .then(response => {
          this.tableData = response.data;
          if (this.tableData.length > 0) {
            this.headers = Object.keys(this.tableData[0]).map(key => ({
              text: key.charAt(0).toUpperCase() + key.slice(1),
              value: key
            }));
          }
        })
        .catch(error => console.error('Error fetching volunteers:', error));
    }
  },
  mounted() {
    this.fetchData();
  }
}
</script>
